### ISSUE TITLE
Extended DNS Error and DNS client

### ISSUE THREAD

**Issue by mglt** [mglt/draft-mglt-dnsop-dnssec-validator-requirements#2]
The resolver should return information on the reasons a DNSSEC validation fails. This provides the DNS client  has a better understanding of the resolution, increases trust in the resolver.

**Comment by bortzmeyer** [comment]
The I-D draft-ietf-dnsop-extended-error just approved by the IESG, provides a good way to do it.

**Comment by mglt** [comment]
RFC8914 is introduced for DNSSEC validation error - including the non support of a deprecated algorithm.
